HSET addressBook "abcd" "{\"firstName\":\"abcd\",\"lastName\":\"abcd\",\"email\":\"abcd\",\"phone\":\"1234567890\",\"Address\":\"abcd hkjhfd \"}"
HSET addressBook "bcda" "{\"firstName\":\"bcda\",\"lastName\":\"bcda\",\"email\":\"bcda\",\"phone\":\"1234567890\",\"Address\":\"bcda hkjhfd \"}"
HSET addressBook "cdab" "{\"firstName\":\"cdab\",\"lastName\":\"cdab\",\"email\":\"cdab\",\"phone\":\"1234567890\",\"Address\":\"cdab hkjhfd \"}"
HSET addressBook "dabc01" "{\"firstName\":\"dabc01\",\"lastName\":\"dabc\",\"email\":\"dabc\",\"phone\":\"1234567890\",\"Address\":\"dabc hkjhfd \"}"
HSET addressBook "dabc02" "{\"firstName\":\"dabc02\",\"lastName\":\"dabc\",\"email\":\"dabc\",\"phone\":\"1234567890\",\"Address\":\"dabc hkjhfd \"}"
HSET addressBook "dabc03" "{\"firstName\":\"dabc03\",\"lastName\":\"dabc\",\"email\":\"dabc\",\"phone\":\"1234567890\",\"Address\":\"dabc hkjhfd \"}"
HSET addressBook "dabc04" "{\"firstName\":\"dabc04\",\"lastName\":\"dabc\",\"email\":\"dabc\",\"phone\":\"1234567890\",\"Address\":\"dabc hkjhfd \"}"
HSET addressBook "dabc05" "{\"firstName\":\"dabc05\",\"lastName\":\"dabc\",\"email\":\"dabc\",\"phone\":\"1234567890\",\"Address\":\"dabc hkjhfd \"}"
HSET addressBook "dabc06" "{\"firstName\":\"dabc06\",\"lastName\":\"dabc\",\"email\":\"dabc\",\"phone\":\"1234567890\",\"Address\":\"dabc hkjhfd \"}"
HSET addressBook "dabc07" "{\"firstName\":\"dabc07\",\"lastName\":\"dabc\",\"email\":\"dabc\",\"phone\":\"1234567890\",\"Address\":\"dabc hkjhfd \"}"
HSET addressBook "dabc08" "{\"firstName\":\"dabc08\",\"lastName\":\"dabc\",\"email\":\"dabc\",\"phone\":\"1234567890\",\"Address\":\"dabc hkjhfd \"}"
HSET addressBook "dabc09" "{\"firstName\":\"dabc09\",\"lastName\":\"dabc\",\"email\":\"dabc\",\"phone\":\"1234567890\",\"Address\":\"dabc hkjhfd \"}"
HSET addressBook "dabc10" "{\"firstName\":\"dabc10\",\"lastName\":\"dabc\",\"email\":\"dabc\",\"phone\":\"1234567890\",\"Address\":\"dabc hkjhfd \"}"
HSET addressBook "dabc11" "{\"firstName\":\"dabc11\",\"lastName\":\"dabc\",\"email\":\"dabc\",\"phone\":\"1234567890\",\"Address\":\"dabc hkjhfd \"}"
HSET addressBook "dabc12" "{\"firstName\":\"dabc12\",\"lastName\":\"dabc\",\"email\":\"dabc\",\"phone\":\"1234567890\",\"Address\":\"dabc hkjhfd \"}"
HSET user "test" "{\"userid\":\"test\",\"password\":\"test\",\"role\":\"user\"}"
